### ISSUE TITLE
zlib SCons config is masked by Python 3 zlib builtin

### ISSUE THREAD

**Issue by str4d** [CauldronDevelopmentLLC/cbang#45]
```
$ scons -C cbang with_openssl=no disable_local=libevent
scons: Entering directory `D:\a\fah-viewer\fah-viewer\cbang'
scons: Reading SConscript files ...
Traceback (most recent call last):
  File "D:\a\fah-viewer\fah-viewer\cbang\config\__init__.py", line 199, in CBTryLoadTool
    env.Tool(name, toolpath = [path])
  File "c:\hostedtoolcache\windows\python\3.8.2\x64\lib\site-packages\scons\SCons\Environment.py", line 1809, in Tool
    tool = SCons.Tool.Tool(tool, toolpath, **kw)
  File "c:\hostedtoolcache\windows\python\3.8.2\x64\lib\site-packages\scons\SCons\Tool\__init__.py", line 122, in __init__
    module = self._tool_module()
  File "c:\hostedtoolcache\windows\python\3.8.2\x64\lib\site-packages\scons\SCons\Tool\__init__.py", line 233, in _tool_module
    if sys_modules_value and sys_modules_value.__file__ == spec.origin:
AttributeError: module 'zlib' has no attribute '__file__'
```

I can build after patching `SCons` to check for the `__file__` attribute before accessing it, but I'm not sure whether this results in the intended behaviour.

**Comment by Gum-Joe** [comment]
Same here.  Your patch worked to help me build it.

**Comment by jcoffland** [comment]
This is really an Scons issue.
